### PR TITLE
Update com.google.drivefs.settings.plist

### PR DESCRIPTION
**Pull request by andrewzirkel**
Add PromptToBackupDevices which can set the Prompt me to back up devices setting.

This setting controls whether the user is prompted to backup external storage devices.

### CODE REVIEW

**Comment by kevinmcox** [comment]
Thanks @andrewzirkel. Where did this setting come from? It isn't in Google's documentation.

**Comment by andrewzirkel** [comment]
It is set by the Google Drive Preferences UI in the com.google.drivefs.settings preferences domain.  I am using it successfully in my environment.  When set the "Prompt me to backup devices" setting is grayed out and the message "This setting is managed by your administrator" appears below.

**Review by kevinmcox — CHANGES_REQUESTED** [review]
Looks good, please also update the values for `pfm_last_modified` on Line 16 and `pfm_version` on Line 426.

**Comment by andrewzirkel** [comment]
Updated pfm_last_modified and pfm_version as requested.

**Review by kevinmcox — APPROVED** [review]
Looks good to me.

**Review by apizz — APPROVED** [review]

**Pull request merged**
