### PR TITLE
DigiDNA Restrictions tweaks

### PR DESCRIPTION
**Pull request by relgit**
This PR makes two miscellaneous tweaks in the Restrictions manifest:
* Removes redundant appearance of key name in segment
*  Adds default value to key

### CODE REVIEW

**Review by kevinmcox — COMMENTED** [review]
Dang this is a massive profile...

Despite having an `AirPlay` section in `pfm_segments` of both the old and updated manifest, I do not get an AirPlay section in the GUI.

**Comment by relgit** [comment]
It's a beast, I know.

Looks like `pfm_range_list_titles` omits AirPlay for some reason. Let me add a commit amending this quickly.

**Comment by relgit** [comment]
There; try when you're ready.

**Comment by relgit** [comment]
Apart for corrections made after discussion in #377, I've now also added a commit removing key-level documentation URLs in two cases where they were equal to the domain's general one.

**Review by apizz — APPROVED** [review]

**Pull request merged**
