### PR TITLE
Add Nudge

### LINKED ISSUE #419: Add Nudge
### Please provide the following information:

**App Name**: Nudge

**App URL**: https://github.com/macadmins/nudge

**App Profile Documentation URL**: https://github.com/macadmins/nudge/wiki/Preferences

**Payload / Domain**: com.github.macadmins.Nudge

### PR DESCRIPTION
**Pull request by apizz**
Closes #419

### CODE REVIEW

**Comment by kkrumm1** [comment]
thank you for all you do. Any word when this will get merged?

**Comment by apizz** [comment]
Unclear. Need to make time to review and I'm not using this myself so if you wanted to test as is you could copy this into your Mac's `~/Library/Application Support/ProfilePayloads/Manifests` folder and quit and reopen ProfileCreator.

IIRC because of how deep the nesting goes there may not be a way to configure all the payload settings within the GUI. Nested dictionaries make things a little challenging.

**Comment by kkrumm1** [comment]
I understand - I will give it test one and let you know. Thanks!

**Comment by apizz** [comment]
Reviewed as best I can.

**Pull request merged**
