### PR TITLE
feat: Add manifest for 1Password 8 on macOS and iOS.

### PR DESCRIPTION
**Pull request by fspeirs**
This PR adds manifests for the new MDM support in 1Password for macOS and iOS.

### CODE REVIEW

**Comment by kevinmcox** [comment]
Quick link to the documentation: https://support.1password.com/mobile-device-management/

**Comment by fspeirs** [comment]
Thanks Kevin. Let me fix that now.

**Comment by fspeirs** [comment]
Ah, just noticed that someone else created an initial manifest. Mine has per-platform support for different key support on macOS and iOS, so it's probably still a worthwile enhancement. Let me close this PR, de-conflict it and I'll send you another one soon.

**Comment by kevinmcox** [comment]
Sounds good!

**Pull request closed without merging**
