### PR TITLE
Update menu.nomad.login.ad.plist

### PR DESCRIPTION
**Pull request by ladygreyjedi**
Changes reflected in Nomad Login 1.4 RC4. https://macadmins.slack.com/archives/C88MFDLV8/p1586456154421100 

Moved design elements such as logos and wallpaper to new pfm_segment Design

### CODE REVIEW

**Comment by apizz** [comment]
Want to help you help yourself, how are you testing your changes? I see bad closing tags.

**Comment by ladygreyjedi** [comment]
I’ll be honest I don’t know how to test it in the app. I wasn’t seeing anything flagged in coderunner.

**Comment by apizz** [comment]
No worries, I still need to create videos for this. I copy my final file into where ProfileCreator stores manifests in ~/Library/Application Support/ProfilePayloads. Think some of this is on the wiki but afk atm.

**Comment by apizz** [comment]
No worries, I still need to create videos for this. I copy my final file into where ProfileCreator stores manifests in ~/Library/Application Support/ProfilePayloads. Think some of this is on the wiki but afk atm.

**Comment by ladygreyjedi** [comment]
Ok. I’ll give it a try tomorrow when I’m working. Might as well get paid for making my life easier :P

**Comment by ladygreyjedi** [comment]
Apizz, I was able to test this in app and its working.

**Pull request merged**
