### PR TITLE
Update of net.glencode.Particulars.plist for Particulars 54

### PR DESCRIPTION
**Pull request by fraserhess**
Hello, I'm the developer of Particulars. I have overhauled and updated this manifest to include all of the app's recent changes.

### CODE REVIEW

**Comment by kevinmcox** [comment]
Thanks @fraserhess!

**Comment by fraserhess** [comment]
Kevin! I may have messed this up. I based my modifications of this the version of manifest from https://github.com/DigiDNA/ProfileManifests/blob/imazing_standard/Manifests/ManagedPreferencesApplications/net.glencode.Particulars.plist thinking I need to submit a pull request to that repo too. I've since read the they should pick up modifications from this repo.

If you wish I can start over from this repo. I have a record of all 32 of the commits I made to a local repo to make this version.

**Comment by relgit** [comment]
@fraserhess thanks for the continued contribution, it's great to have first-party collaboration.

Now, the only differences between the fork and the upstream right now for this particular file are the descriptions for the `Payload...` subkeys at the top. Since the ones that you picked up are the new official ones from Apple, you can just leave them there.

The changes look good to me, but I do have one comment, and that is that I can see that there are some new boolean subkeys that have no default values. For example, `diskFreeSpaceNonBootVolumes`, `hideDockIcon`, `ignoreHiding`, and `operatingSystemVersionName`. Assuming that there are default values, could you please add those?

**Review by relgit — CHANGES_REQUESTED** [review]
Please add default boolean values.

**Comment by fraserhess** [comment]
I have added another commit with the requested changes

**Review by relgit — APPROVED** [review]

**Comment by relgit** [comment]
Thanks @fraserhess _!_

**Comment by fraserhess** [comment]
@relgit I'm asking as you as you seem to be the maintainer for the imazing fork. When I can expect this to be merged into https://github.com/DigiDNA/ProfileManifests? thanks

**Comment by relgit** [comment]
You'll be happy to know that it was just merged.

**Pull request merged**
