### PR TITLE
manifest update for xcreds 4

### PR DESCRIPTION
**Pull request by twocanoes**
manifest update for xcreds 4

### CODE REVIEW

**Review by kevinmcox — CHANGES_REQUESTED** [review]
Line 16 needs to be updated and Line 1064 needs to be incremented please.

**Comment by twocanoes** [comment]
Done. please review. thanks!

**Comment by twocanoes** [comment]
Updated with changes requested. Please accept :)

**Review by relgit — APPROVED** [review]
Thanks 😃

**Pull request merged**
