### PR TITLE
Adding Jamf Trust

### PR DESCRIPTION
**Pull request by txhaflaire**
Adding  ProfileManifest forJamf Trust

### CODE REVIEW

**Comment by txhaflaire** [comment]
Hey @kevinmcox i'm new at contributing to this repo, anything needed from my side to have it merged / reviewed?

Thanks!

**Comment by kevinmcox** [comment]
Hey @txhaflaire, we appreciate the contribution!

At this point we just need a couple of us to make time to review it. Hopefully we won't leave you hanging too long. 😎

**Comment by txhaflaire** [comment]
@kevinmcox Alright - thanks in advance already for all the efforts!

**Review by apizz — APPROVED** [review]
lgtm, thank you!

**Pull request merged**
