### PR TITLE
Update Brave manifest

### LINKED ISSUE #331: Update Brave Manifest
### Please provide the following information:

Per #330, use ChromeToBrave.py script

**Name of App / Payload**: Brave

**Preference key(s) to be added / updated**: N/A

**Applicable Preference Documentation URL(s)**: N/A

### PR DESCRIPTION
**Pull request by apizz**
Closes #331

### CODE REVIEW

**Comment by apizz** [comment]
@relgit want to get your eyes on the improvements I made to the ChromeToBrave.py script.  Let me know what you think whenever you have a chance :)

**Comment by relgit** [comment]
All good with me, though one small tip if I may is that if you keep `brave_domain` and `chrome_domain` out of the dictionary, you could then keep the iteration improvement you made, iterate on the dictionary's keys, and save yourself the need for the exception catching block.

**Comment by apizz** [comment]
Great suggestion, thank you. I'll make that change.

**Comment by apizz** [comment]
@relgit Should be all set now.  Can I get a 👍  on the review pls :)

**Comment by apizz** [comment]
My first real work with data structures in Python, so thank you! :)

**Pull request merged**
